### Imports

In [37]:
import torch
import torch_geometric.nn as pyg_nn
import torch.nn.functional as F

### Below we specify arbitrary constants or hiperparams

`TEST_TRAIN_SPLIT` - test size (0.2 == 20%) <br>
`ROWS_PER_EXAMPLE` - number of rows (key presses) per data chunk <br>
`NUM_HIDDEN_DIMS` - TODO <br>
`NUM_EPOCHS` - number of training epochs

In [38]:
TEST_TRAIN_SPLIT = 0.2
ROWS_PER_EXAMPLE = 150
NUM_HIDDEN_DIMS = 64
NUM_EPOCHS = 1000

file_names = ["datasets/key_presses (1).tsv", "datasets/key_presses (2).tsv", "datasets/key_presses (3).tsv", "datasets/key_presses (4).tsv"]

In [39]:

# Define a simple GCN model
class LetterGNN(torch.nn.Module):
    def __init__(self, num_node_features, hidden_dim, num_classes, num_layers=2):
        super(LetterGNN, self).__init__()

        self.convs = torch.nn.ModuleList()
        self.convs.append(pyg_nn.GCNConv(num_node_features, hidden_dim))
        for _ in range(num_layers - 1):
            self.convs.append(pyg_nn.GCNConv(hidden_dim, hidden_dim))

        self.fc = torch.nn.Linear(hidden_dim, num_classes)

    def forward(self, x, edge_index, batch):
        for conv in self.convs:
            x = x.float()
            edge_index = edge_index.long()
            x = conv.forward(x, edge_index)
            x = F.relu(x)
        
        # idk maybe use a different pool method 
        x = pyg_nn.global_mean_pool(x, batch)

        # classify
        x = self.fc(x)

        return x
        


Take a look at `dataset.x size`. Size (13, 5) means there is 13 different letters in data chunk, 5 attributes for each letter.

In [40]:
from torch_geometric.data import InMemoryDataset
from sklearn.model_selection import train_test_split
import data_loader

mode = data_loader.load_char_mode.DROP
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# This is a list of lists of Data objects - datasets
# each dataset comes from a different input file - a different user
list_of_datasets = [data_loader.load_data_object(filename, mode=mode, y=torch.tensor([i]), rows_per_example=ROWS_PER_EXAMPLE)
                     for i, filename in enumerate(file_names)]

num_features = list_of_datasets[0][0].x.shape[1]

print("Number of examples: ", sum(len(l) for l in list_of_datasets))
print("Shape of dataset.x: ", tuple(list_of_datasets[0][0].x.shape))

Number of examples:  72
Shape of dataset.x:  (24, 2)


In [41]:
from collections import Counter

training_dataset_pos = []
testing_dataset_pos = []
training_dataset_neg = []
testing_dataset_neg = []

# !!! choose which one get the positive label
positive_index = 2 # just arbitrary

# relabel the datasets
for i, dataset in enumerate(list_of_datasets):
    for item in dataset:
        if i == positive_index:
            item.y = torch.tensor([1])
        else:
            item.y = torch.tensor([0])

    train_items, test_items = train_test_split(dataset, test_size=TEST_TRAIN_SPLIT)
    
    if i == positive_index:
        training_dataset_pos.extend(train_items)
        testing_dataset_pos.extend(test_items)
    else:
        training_dataset_neg.extend(train_items)
        testing_dataset_neg.extend(test_items)


class SimpleGraphDataset(InMemoryDataset):
    def __init__(self, data_list):
        super(SimpleGraphDataset, self).__init__('.', None, None, None)
        self.data, self.slices = self.collate(data_list)  # Collate all data objects

    def __len__(self):
        return len(self.data.y)  # Number of graphs in the dataset
    
    def statistics(self) -> str:
        class_counts = Counter(self.data.y.cpu().numpy())
        return " | ".join([f"{item_class}: {count}" for item_class, count in class_counts.items()]) + f" | Total: {sum(class_counts.values())}"
        

train_items = [e.to(device) for e in (training_dataset_pos + training_dataset_neg)]
test_items = [e.to(device) for e in (testing_dataset_pos + testing_dataset_neg)]

dataset = SimpleGraphDataset(train_items)
test_dataset = SimpleGraphDataset(test_items)

print("Train dataset statistics: ", dataset.statistics())
print("Test dataset statistics:  ", test_dataset.statistics())

Train dataset statistics:  1: 14 | 0: 42 | Total: 56
Test dataset statistics:   1: 4 | 0: 12 | Total: 16


In [42]:
# Train the model 

from torch_geometric.loader import DataLoader
# Q: How Do we choose hidden dims size ?? !!!!!!!!!!

# Define the model, loss, and optimizer
model = LetterGNN(num_node_features=dataset.num_node_features, hidden_dim=NUM_HIDDEN_DIMS, num_classes=dataset.num_classes).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = torch.nn.CrossEntropyLoss()

# Train loop
def train(model, data_loader):
    model.train()
    total_loss = 0
    for data in data_loader:
        optimizer.zero_grad()
        output = model(data.x, data.edge_index, data.batch)  # Forward pass
        loss = criterion(output, data.y)  # Compute the loss
        loss.backward()  # Backpropagation
        optimizer.step()  # Update the model parameters
        total_loss += loss.item()
    return total_loss / len(data_loader)


# Training over epochs
data_loader = DataLoader(dataset, batch_size=32, shuffle=True)
prev_loss = 100000
for epoch in range(1, NUM_EPOCHS):
    loss = train(model, data_loader)
    if epoch % 50 == 0 or epoch == NUM_EPOCHS-1:
        print(f"Epoch: {epoch:03d}, Loss: {loss:.4f}")
    if round(loss, 3) == 0:
        print(f"Epoch: {epoch:03d}, Loss: {loss:.4f}")
        break

/home/filip/Documents/.venvs/gnn/lib/python3.12/site-packages/torch_geometric/data/in_memory_dataset.py:300: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. The data of the dataset is already cached, so any modifications to `data` will not be reflected when accessing its elements. Clearing the cache now by removing all elements in `dataset._data_list`. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)


Epoch: 050, Loss: 0.4093
Epoch: 100, Loss: 0.3919
Epoch: 150, Loss: 0.3871
Epoch: 200, Loss: 0.4612
Epoch: 250, Loss: 0.3164
Epoch: 300, Loss: 0.2984
Epoch: 350, Loss: 0.2988
Epoch: 400, Loss: 0.2580
Epoch: 450, Loss: 0.2650
Epoch: 500, Loss: 0.2642
Epoch: 550, Loss: 0.3082
Epoch: 600, Loss: 0.1967
Epoch: 650, Loss: 0.1937
Epoch: 700, Loss: 0.2020
Epoch: 750, Loss: 0.2116
Epoch: 800, Loss: 0.1745
Epoch: 850, Loss: 0.2496
Epoch: 900, Loss: 0.4065
Epoch: 950, Loss: 0.2068
Epoch: 999, Loss: 0.1860


In [43]:
# test 
def test(model, data_loader):
    model.eval()
    correct = 0
    for data in data_loader:
        output = model(data.x, data.edge_index, data.batch)
        pred = output.argmax(dim=1)  # Get the index of the max log-probability
        # print(f"Correct {data.y[0]} Pred {pred[0]}")
        if pred != data.y:
            print(output[0])
        correct += (pred == data.y).sum().item()
    return correct / len(data_loader.dataset)

def test_acc():
    # Test the model
    test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)
    accuracy = test(model, test_loader)
    print(f"Test Accuracy: {accuracy:.4f}")

test_acc()

tensor([-3.5694, -3.9978], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([-3.4760, -4.1096], device='cuda:0', grad_fn=<SelectBackward0>)
tensor([-3.5617, -3.0261], device='cuda:0', grad_fn=<SelectBackward0>)
Test Accuracy: 0.8125
